### ISSUE TITLE
Plugins not working in Elagto Wavelink

### ISSUE THREAD

**Issue by eliasstepanik** [xoofx/NPlug#2]
## Issue Title
**Plugins not working in Elgato WaveLink**

## Steps to reproduce
1. Place the plugin files in the VST3 folder.
2. Hit refresh in Elgato WaveLink.

## Issue description
I'm experiencing an issue where plugins are not working in Elgato WaveLink. After placing the files in the VST3 folder and hitting refresh in WaveLink, the plugins still don't seem to function properly. It says that it is uncompatible.

**Comment by eliasstepanik** [comment]
> ## Issue Title
> **Plugins not working in Elgato WaveLink**
> 
> ## Steps to reproduce
> 1. Place the plugin files in the VST3 folder.
> 2. Hit refresh in Elgato WaveLink.
> 
> ## Issue description
> I'm experiencing an issue where plugins are not working in Elgato WaveLink. After placing the files in the VST3 folder and hitting refresh in WaveLink, the plugins still don't seem to function properly. It says that it is uncompatible.

Audacity does also not seem to work.

**Comment by xoofx** [comment]
Just tried with Audacity 3.2.5 on Windows and SimpleDelay is working fine:

![image](https://user-images.githubusercontent.com/715038/233784164-b5a7cbce-7667-457d-8239-39cff0f07042.png)

So there is something different on your side that makes it not working (what is the OS? when you say place the plugin files, which files exactly?...etc.)

It is impossible to investigate anything from the short description you provide.
